### ISSUE TITLE
Inconsistent numbers height

### ISSUE THREAD

**Issue by yukina3230** [aaronmbos/monocode#22]
For some reasons, the number 9 seems shorter in my VSCode. (This issue is not appear when the font size is greater than 14)

![image](https://github.com/aaronmbos/monocode/assets/75545944/d4c0089d-c8d7-4a7a-9f33-e33b1956292f)

**Comment by aaronmbos** [comment]
Thanks for filing this issue!

I was actually planning to revert the shape of 6 and 9 to the default Iosevka variant respectively in the next release.

I don't know for sure if that will solve the issue, but I think it will.

**Comment by aaronmbos** [comment]
Here is a WIP build that you can unzip and install. The only characters that have changed are 6 and 9. If this resolves the issue, I'll publish a new version with these modifications.

https://github.com/aaronmbos/monocode/suites/15258748206/artifacts/871783131

<img width="53" alt="image" src="https://github.com/aaronmbos/monocode/assets/24758740/f00c6a67-326d-4d78-b6f7-c4f7ae161d36">

**Comment by yukina3230** [comment]
Thanks, I've tried this, it's fixed now.
